[package]
name = "parcel_sourcemap"
version = "2.0.0-rc.7"
authors = [ "Jasper De Moor <jasperdemoor@gmail.com>" ]
edition = "2018"
description = "Parcel Source Map Library"
license = "MIT"
keywords = [ "sourcemap", "Node", "Parcel" ]
repository = "https://github.com/parcel-bundler/source-map"

[dependencies]
"vlq" = "0.5.1"
"napi" = "1.6.1"
rkyv = "0.6.7"
"js-sys" = "0.3"
"wasm-bindgen" = "0.2"
