name: Lint
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint SourceCode
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: default
          override: true
          components: rustfmt, clippy

      # Should use comitted lockfile
      # - name: Generate Cargo.lock
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: generate-lockfile

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: lint-cargo-registry-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: lint-cargo-index-trimmed-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-features

      - name: Clear the cargo caches
        run: |
          cargo install cargo-cache --no-default-features --features ci-autoclean
          cargo-cache

